### ISSUE TITLE
ID issue

### ISSUE THREAD

**Issue by PaciorekMichal** [niteraleph/Serwis-przychodnia#5]
Zdecydowaliśmy się usunąć ID pacjentów, lekarzy, ponieważ tak naprawdę pesel jest również unikatową liczbą którą możemy używać do np. wyszukiwania potrzebnych nam elementów. Pesel jest również bardziej intuicyjny ponieważ podaje się go przy rejestracji i nie ma potrzeby specjalnie go generować. Ewentualnie trzeba pamiętać o zapytanie pacjenta/ lekarza o zgodę na przetwarzanie danych osobowych.

**Comment by niteraleph** [comment]
Akceptuję zmianę, pesel może służyć za identyfikację
