### ISSUE TITLE
Terminarz

### ISSUE THREAD

**Issue by PaciorekMichal** [niteraleph/Serwis-przychodnia#6]
Terminarz miał przechowywać miesięczną rozpiskę zaplanowanych wizyt. Miało to działać na zasadzie listy wizyt dla każdego doktora, ale stwierdziliśmy, że prościej to zaimplementować jako tablicę dwuwymiarową (godzin do dni) która będzie przechowywać wstępnie same zera. Wpisanie wizyt będzie działać na zasadzie podstawienia za zero peselu umówionego pacjenta, dzięki temu będziemy wiedzieć czy dany termin jest zajęty (różne od zera) i wiedzieć jaki pacjent ma u danego doktora wizytę.

**Comment by niteraleph** [comment]
Terminarz pozostaje jednak klasą, niemniej klasa wizyta nie jest używana gdyż terminarz wystarcza
